server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atliao/springcloud-config.git  #GitHub上面的git仓库名字 这里可以写https地址跟ssh地址，https地址需要配置username和password
          username: atliao
          password: liao15184335457
          default-label: main #新建的github分支已经默认为main，所以此处需指定 spring.cloud.config.server.git.default-label=main
          ####搜索目录
          search-paths:
            - springcloud-config
      ####读取分支
      label: main   # 以前是master,现在是叫main


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


